// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lobby_club_enum.proto

package club

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClubReplyCode int32

const (
	ClubReplyCode_RCNone      ClubReplyCode = 0
	ClubReplyCode_RCError     ClubReplyCode = 1
	ClubReplyCode_RCOperation ClubReplyCode = 2
)

var ClubReplyCode_name = map[int32]string{
	0: "RCNone",
	1: "RCError",
	2: "RCOperation",
}

var ClubReplyCode_value = map[string]int32{
	"RCNone":      0,
	"RCError":     1,
	"RCOperation": 2,
}

func (x ClubReplyCode) Enum() *ClubReplyCode {
	p := new(ClubReplyCode)
	*p = x
	return p
}

func (x ClubReplyCode) String() string {
	return proto.EnumName(ClubReplyCode_name, int32(x))
}

func (x *ClubReplyCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClubReplyCode_value, data, "ClubReplyCode")
	if err != nil {
		return err
	}
	*x = ClubReplyCode(value)
	return nil
}

func (ClubReplyCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953a149cff643cc3, []int{0}
}

// 俱乐部角色定义
type ClubRoleType int32

const (
	ClubRoleType_CRoleTypeNone    ClubRoleType = 0
	ClubRoleType_CRoleTypeMember  ClubRoleType = 1
	ClubRoleType_CRoleTypeCreator ClubRoleType = 2
	// CRoleTypeOwner = 4; // 拥有者
	ClubRoleType_CRoleTypeMgr ClubRoleType = 3
)

var ClubRoleType_name = map[int32]string{
	0: "CRoleTypeNone",
	1: "CRoleTypeMember",
	2: "CRoleTypeCreator",
	3: "CRoleTypeMgr",
}

var ClubRoleType_value = map[string]int32{
	"CRoleTypeNone":    0,
	"CRoleTypeMember":  1,
	"CRoleTypeCreator": 2,
	"CRoleTypeMgr":     3,
}

func (x ClubRoleType) Enum() *ClubRoleType {
	p := new(ClubRoleType)
	*p = x
	return p
}

func (x ClubRoleType) String() string {
	return proto.EnumName(ClubRoleType_name, int32(x))
}

func (x *ClubRoleType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClubRoleType_value, data, "ClubRoleType")
	if err != nil {
		return err
	}
	*x = ClubRoleType(value)
	return nil
}

func (ClubRoleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953a149cff643cc3, []int{1}
}

type ClubOperError int32

const (
	ClubOperError_CERR_OK                               ClubOperError = 0
	ClubOperError_CERR_Exceed_Max_Club_Count_Limit      ClubOperError = 1
	ClubOperError_CERR_No_Valid_Club_Number             ClubOperError = 2
	ClubOperError_CERR_Database_IO                      ClubOperError = 3
	ClubOperError_CERR_Encode_Decode                    ClubOperError = 4
	ClubOperError_CERR_Invalid_Input_Parameter          ClubOperError = 5
	ClubOperError_CERR_Only_Creator_And_Mgr_Can_KickOut ClubOperError = 6
	ClubOperError_CERR_You_Already_In_Club              ClubOperError = 7
	ClubOperError_CERR_You_Are_In_Club_Block_List       ClubOperError = 8
	ClubOperError_CERR_You_Already_Applicate            ClubOperError = 9
	ClubOperError_CERR_Invitee_Already_In_Club          ClubOperError = 10
	ClubOperError_CERR_Invitee_Are_In_Club_Block_List   ClubOperError = 11
	ClubOperError_CERR_Invitee_Already_Applicate        ClubOperError = 12
	ClubOperError_CERR_Club_Not_Exist                   ClubOperError = 13
	ClubOperError_CERR_Only_Creator_Can_Invite          ClubOperError = 14
	ClubOperError_CERR_Only_Creator_And_Mgr_Can_Approve ClubOperError = 15
	ClubOperError_CERR_No_Applicant                     ClubOperError = 16
	ClubOperError_CERR_Applicant_Already_In_Club        ClubOperError = 17
	ClubOperError_CERR_Applicant_In_Club_Block_List     ClubOperError = 18
	ClubOperError_CERR_Token_Invalid                    ClubOperError = 19
	ClubOperError_CERR_Club_Name_Too_Long               ClubOperError = 20
	ClubOperError_CERR_Club_Name_Exist                  ClubOperError = 21
	ClubOperError_CERR_Club_Only_Owner_Can_Disband      ClubOperError = 22
	ClubOperError_CERR_Owner_Can_not_quit               ClubOperError = 23
	ClubOperError_CERR_User_Not_In_Club                 ClubOperError = 24
	ClubOperError_CERR_Club_Only_Owner_And_Mgr_Can_Set  ClubOperError = 25
	ClubOperError_CERR_Club_Forbit_Join                 ClubOperError = 26
	ClubOperError_CERR_Input_Text_Too_Long              ClubOperError = 27
	ClubOperError_CERR_Club_Has_Room_In_PlayingState    ClubOperError = 28
	ClubOperError_CERR_Can_Not_Kick_Out_Creator_Or_Mgr  ClubOperError = 29
)

var ClubOperError_name = map[int32]string{
	0:  "CERR_OK",
	1:  "CERR_Exceed_Max_Club_Count_Limit",
	2:  "CERR_No_Valid_Club_Number",
	3:  "CERR_Database_IO",
	4:  "CERR_Encode_Decode",
	5:  "CERR_Invalid_Input_Parameter",
	6:  "CERR_Only_Creator_And_Mgr_Can_KickOut",
	7:  "CERR_You_Already_In_Club",
	8:  "CERR_You_Are_In_Club_Block_List",
	9:  "CERR_You_Already_Applicate",
	10: "CERR_Invitee_Already_In_Club",
	11: "CERR_Invitee_Are_In_Club_Block_List",
	12: "CERR_Invitee_Already_Applicate",
	13: "CERR_Club_Not_Exist",
	14: "CERR_Only_Creator_Can_Invite",
	15: "CERR_Only_Creator_And_Mgr_Can_Approve",
	16: "CERR_No_Applicant",
	17: "CERR_Applicant_Already_In_Club",
	18: "CERR_Applicant_In_Club_Block_List",
	19: "CERR_Token_Invalid",
	20: "CERR_Club_Name_Too_Long",
	21: "CERR_Club_Name_Exist",
	22: "CERR_Club_Only_Owner_Can_Disband",
	23: "CERR_Owner_Can_not_quit",
	24: "CERR_User_Not_In_Club",
	25: "CERR_Club_Only_Owner_And_Mgr_Can_Set",
	26: "CERR_Club_Forbit_Join",
	27: "CERR_Input_Text_Too_Long",
	28: "CERR_Club_Has_Room_In_PlayingState",
	29: "CERR_Can_Not_Kick_Out_Creator_Or_Mgr",
}

var ClubOperError_value = map[string]int32{
	"CERR_OK":                               0,
	"CERR_Exceed_Max_Club_Count_Limit":      1,
	"CERR_No_Valid_Club_Number":             2,
	"CERR_Database_IO":                      3,
	"CERR_Encode_Decode":                    4,
	"CERR_Invalid_Input_Parameter":          5,
	"CERR_Only_Creator_And_Mgr_Can_KickOut": 6,
	"CERR_You_Already_In_Club":              7,
	"CERR_You_Are_In_Club_Block_List":       8,
	"CERR_You_Already_Applicate":            9,
	"CERR_Invitee_Already_In_Club":          10,
	"CERR_Invitee_Are_In_Club_Block_List":   11,
	"CERR_Invitee_Already_Applicate":        12,
	"CERR_Club_Not_Exist":                   13,
	"CERR_Only_Creator_Can_Invite":          14,
	"CERR_Only_Creator_And_Mgr_Can_Approve": 15,
	"CERR_No_Applicant":                     16,
	"CERR_Applicant_Already_In_Club":        17,
	"CERR_Applicant_In_Club_Block_List":     18,
	"CERR_Token_Invalid":                    19,
	"CERR_Club_Name_Too_Long":               20,
	"CERR_Club_Name_Exist":                  21,
	"CERR_Club_Only_Owner_Can_Disband":      22,
	"CERR_Owner_Can_not_quit":               23,
	"CERR_User_Not_In_Club":                 24,
	"CERR_Club_Only_Owner_And_Mgr_Can_Set":  25,
	"CERR_Club_Forbit_Join":                 26,
	"CERR_Input_Text_Too_Long":              27,
	"CERR_Club_Has_Room_In_PlayingState":    28,
	"CERR_Can_Not_Kick_Out_Creator_Or_Mgr":  29,
}

func (x ClubOperError) Enum() *ClubOperError {
	p := new(ClubOperError)
	*p = x
	return p
}

func (x ClubOperError) String() string {
	return proto.EnumName(ClubOperError_name, int32(x))
}

func (x *ClubOperError) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClubOperError_value, data, "ClubOperError")
	if err != nil {
		return err
	}
	*x = ClubOperError(value)
	return nil
}

func (ClubOperError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953a149cff643cc3, []int{2}
}

type ClubEventType int32

const (
	ClubEventType_CEVT_None         ClubEventType = 0
	ClubEventType_CEVT_ClubDisband  ClubEventType = 1
	ClubEventType_CEVT_NewApplicant ClubEventType = 2
	ClubEventType_CEVT_Approval     ClubEventType = 3
	ClubEventType_CEVT_Deny         ClubEventType = 4
	ClubEventType_CEVT_Join         ClubEventType = 5
	ClubEventType_CEVT_Quit         ClubEventType = 6
	ClubEventType_CEVT_Kickout      ClubEventType = 7
)

var ClubEventType_name = map[int32]string{
	0: "CEVT_None",
	1: "CEVT_ClubDisband",
	2: "CEVT_NewApplicant",
	3: "CEVT_Approval",
	4: "CEVT_Deny",
	5: "CEVT_Join",
	6: "CEVT_Quit",
	7: "CEVT_Kickout",
}

var ClubEventType_value = map[string]int32{
	"CEVT_None":         0,
	"CEVT_ClubDisband":  1,
	"CEVT_NewApplicant": 2,
	"CEVT_Approval":     3,
	"CEVT_Deny":         4,
	"CEVT_Join":         5,
	"CEVT_Quit":         6,
	"CEVT_Kickout":      7,
}

func (x ClubEventType) Enum() *ClubEventType {
	p := new(ClubEventType)
	*p = x
	return p
}

func (x ClubEventType) String() string {
	return proto.EnumName(ClubEventType_name, int32(x))
}

func (x *ClubEventType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClubEventType_value, data, "ClubEventType")
	if err != nil {
		return err
	}
	*x = ClubEventType(value)
	return nil
}

func (ClubEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953a149cff643cc3, []int{3}
}

type ClubFundEventType int32

const (
	ClubFundEventType_CFET_None            ClubFundEventType = 0
	ClubFundEventType_CFET_Add_By_Shop     ClubFundEventType = 1
	ClubFundEventType_CFET_Award_By_System ClubFundEventType = 3
	ClubFundEventType_CFET_Gift_By_System  ClubFundEventType = 4
	ClubFundEventType_CFET_Reduce_By_Room  ClubFundEventType = 5
	ClubFundEventType_CFET_Add_By_Room     ClubFundEventType = 6
)

var ClubFundEventType_name = map[int32]string{
	0: "CFET_None",
	1: "CFET_Add_By_Shop",
	3: "CFET_Award_By_System",
	4: "CFET_Gift_By_System",
	5: "CFET_Reduce_By_Room",
	6: "CFET_Add_By_Room",
}

var ClubFundEventType_value = map[string]int32{
	"CFET_None":            0,
	"CFET_Add_By_Shop":     1,
	"CFET_Award_By_System": 3,
	"CFET_Gift_By_System":  4,
	"CFET_Reduce_By_Room":  5,
	"CFET_Add_By_Room":     6,
}

func (x ClubFundEventType) Enum() *ClubFundEventType {
	p := new(ClubFundEventType)
	*p = x
	return p
}

func (x ClubFundEventType) String() string {
	return proto.EnumName(ClubFundEventType_name, int32(x))
}

func (x *ClubFundEventType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClubFundEventType_value, data, "ClubFundEventType")
	if err != nil {
		return err
	}
	*x = ClubFundEventType(value)
	return nil
}

func (ClubFundEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953a149cff643cc3, []int{4}
}

type ClubNotifyType int32

const (
	ClubNotifyType_CNotify_None               ClubNotifyType = 0
	ClubNotifyType_CNotify_Change_Member_Role ClubNotifyType = 1
)

var ClubNotifyType_name = map[int32]string{
	0: "CNotify_None",
	1: "CNotify_Change_Member_Role",
}

var ClubNotifyType_value = map[string]int32{
	"CNotify_None":               0,
	"CNotify_Change_Member_Role": 1,
}

func (x ClubNotifyType) Enum() *ClubNotifyType {
	p := new(ClubNotifyType)
	*p = x
	return p
}

func (x ClubNotifyType) String() string {
	return proto.EnumName(ClubNotifyType_name, int32(x))
}

func (x *ClubNotifyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClubNotifyType_value, data, "ClubNotifyType")
	if err != nil {
		return err
	}
	*x = ClubNotifyType(value)
	return nil
}

func (ClubNotifyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953a149cff643cc3, []int{5}
}

func init() {
	proto.RegisterEnum("club.ClubReplyCode", ClubReplyCode_name, ClubReplyCode_value)
	proto.RegisterEnum("club.ClubRoleType", ClubRoleType_name, ClubRoleType_value)
	proto.RegisterEnum("club.ClubOperError", ClubOperError_name, ClubOperError_value)
	proto.RegisterEnum("club.ClubEventType", ClubEventType_name, ClubEventType_value)
	proto.RegisterEnum("club.ClubFundEventType", ClubFundEventType_name, ClubFundEventType_value)
	proto.RegisterEnum("club.ClubNotifyType", ClubNotifyType_name, ClubNotifyType_value)
}

func init() { proto.RegisterFile("lobby_club_enum.proto", fileDescriptor_953a149cff643cc3) }

var fileDescriptor_953a149cff643cc3 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdb, 0x52, 0x1b, 0x47,
	0x10, 0xb5, 0xb8, 0xc6, 0x0d, 0x98, 0x66, 0x00, 0x03, 0x36, 0x76, 0x1c, 0x5f, 0x72, 0xd1, 0x43,
	0xde, 0xf3, 0x28, 0x16, 0x91, 0x28, 0x06, 0xc9, 0x59, 0x14, 0xaa, 0xf2, 0x92, 0xae, 0x59, 0x6d,
	0x5b, 0xde, 0x62, 0x35, 0xb3, 0x19, 0xcd, 0x82, 0xf6, 0x57, 0x52, 0x95, 0xff, 0xca, 0xe7, 0xa4,
	0x66, 0x56, 0xda, 0x95, 0x40, 0x55, 0x79, 0xda, 0xea, 0xcb, 0x9e, 0x3e, 0xa7, 0xbb, 0xa7, 0xe1,
	0x30, 0xd5, 0x51, 0x54, 0xd0, 0x20, 0xcd, 0x23, 0x62, 0x95, 0x8f, 0x7e, 0xcc, 0x8c, 0xb6, 0x5a,
	0xac, 0x39, 0x47, 0xf3, 0x27, 0xd8, 0x09, 0xd2, 0x3c, 0x0a, 0x39, 0x4b, 0x8b, 0x40, 0xc7, 0x2c,
	0x00, 0x36, 0xc2, 0xa0, 0xab, 0x15, 0xe3, 0x13, 0xb1, 0x05, 0x9b, 0x61, 0xd0, 0x36, 0x46, 0x1b,
	0x6c, 0x88, 0x5d, 0xd8, 0x0a, 0x83, 0x5e, 0xc6, 0x46, 0xda, 0x44, 0x2b, 0x5c, 0x69, 0xfe, 0x09,
	0xdb, 0xfe, 0x57, 0x9d, 0x72, 0xbf, 0xc8, 0x58, 0xec, 0xc1, 0x4e, 0x30, 0x33, 0xa6, 0x00, 0xfb,
	0xb0, 0x5b, 0xb9, 0xae, 0x78, 0x14, 0xb1, 0x03, 0x3a, 0x00, 0xac, 0x9c, 0x81, 0x61, 0x69, 0xb5,
	0xc1, 0x15, 0x81, 0xb0, 0x5d, 0xa7, 0x0e, 0x0d, 0xae, 0x36, 0xff, 0xdd, 0x2c, 0xb9, 0xb9, 0x9a,
	0x9e, 0x84, 0xe3, 0x13, 0xb4, 0xc3, 0x90, 0x7a, 0x1f, 0xf1, 0x89, 0x78, 0x0f, 0x6f, 0xbc, 0xd1,
	0x9e, 0x0c, 0x98, 0x63, 0xba, 0x92, 0x13, 0x72, 0xd9, 0x14, 0xe8, 0x5c, 0x59, 0xba, 0x4c, 0x46,
	0x89, 0xc5, 0x86, 0x78, 0x05, 0x27, 0x3e, 0xab, 0xab, 0xe9, 0x46, 0xa6, 0x49, 0x5c, 0xe6, 0x74,
	0x73, 0xcf, 0x65, 0xc5, 0x73, 0x71, 0xe1, 0x73, 0x69, 0x65, 0x24, 0xc7, 0x4c, 0x9d, 0x1e, 0xae,
	0x8a, 0xe7, 0x20, 0x4a, 0x68, 0x35, 0xd0, 0x31, 0xd3, 0x39, 0xbb, 0x0f, 0xae, 0x89, 0x37, 0x70,
	0xea, 0xfd, 0x1d, 0x75, 0xe7, 0xb1, 0x3a, 0x2a, 0xcb, 0x2d, 0x7d, 0x92, 0x46, 0x8e, 0xd8, 0xb2,
	0xc1, 0x75, 0xf1, 0x03, 0x7c, 0x28, 0x19, 0xaa, 0xb4, 0xa0, 0xa9, 0x38, 0x6a, 0xa9, 0x98, 0xae,
	0x86, 0x86, 0x02, 0xa9, 0xe8, 0x63, 0x32, 0xb8, 0xed, 0xe5, 0x16, 0x37, 0xc4, 0x29, 0x1c, 0xfb,
	0xd4, 0x3f, 0x74, 0x4e, 0xad, 0xd4, 0xb0, 0x8c, 0x0b, 0xea, 0x28, 0xcf, 0x0f, 0x37, 0xc5, 0x3b,
	0xf8, 0xba, 0x8e, 0x1a, 0x9e, 0x45, 0xe8, 0x2c, 0xd5, 0x83, 0x5b, 0xba, 0x4c, 0xc6, 0x16, 0xbf,
	0x12, 0xaf, 0xe1, 0xc5, 0x23, 0x88, 0x56, 0x96, 0xa5, 0xc9, 0x40, 0x5a, 0xc6, 0xa7, 0xf3, 0x7c,
	0x13, 0xcb, 0xfc, 0xa8, 0x0c, 0x88, 0xef, 0xe0, 0xdd, 0x62, 0xc6, 0xf2, 0x52, 0x5b, 0xe2, 0x2d,
	0xbc, 0x5e, 0x0a, 0x55, 0x97, 0xdb, 0x16, 0x47, 0xb0, 0xef, 0x73, 0xca, 0x16, 0x6b, 0x4b, 0xed,
	0x89, 0xfb, 0x79, 0xa7, 0xe2, 0xb1, 0xd0, 0x15, 0xd7, 0x8d, 0x12, 0x0d, 0x9f, 0xfd, 0x7f, 0xdf,
	0x5a, 0x59, 0x66, 0xf4, 0x1d, 0xe3, 0xae, 0x38, 0x84, 0xbd, 0xd9, 0x44, 0xa7, 0xc5, 0x95, 0x45,
	0xac, 0x08, 0x56, 0xbe, 0x47, 0x6a, 0xf7, 0xc4, 0x07, 0xf8, 0xe6, 0x41, 0xce, 0x12, 0xad, 0xa2,
	0x1a, 0x7f, 0x5f, 0xdf, 0xb2, 0x9a, 0x0d, 0x1b, 0xf7, 0xc5, 0x4b, 0x38, 0x9a, 0xd3, 0x27, 0x47,
	0x4c, 0x7d, 0xad, 0xe9, 0x52, 0xab, 0x21, 0x1e, 0x88, 0x63, 0x38, 0x78, 0x10, 0x2c, 0xd5, 0x1f,
	0x56, 0x8b, 0xea, 0x23, 0x5e, 0x60, 0xef, 0x5e, 0x71, 0x29, 0xeb, 0x3c, 0x19, 0x47, 0x52, 0xc5,
	0xf8, 0xbc, 0x02, 0xaf, 0x63, 0x4a, 0x5b, 0xfa, 0x2b, 0x4f, 0x2c, 0x1e, 0x89, 0x13, 0x38, 0xf4,
	0xc1, 0xdf, 0xc7, 0x6c, 0x7c, 0x67, 0x67, 0x9a, 0x8e, 0xc5, 0xf7, 0xf0, 0x7e, 0x29, 0xfa, 0x7c,
	0xf3, 0xae, 0xd9, 0xe2, 0x49, 0x05, 0xe2, 0x33, 0x2f, 0xb4, 0x89, 0x12, 0x4b, 0xbf, 0xea, 0x44,
	0xe1, 0x8b, 0x6a, 0x17, 0xcb, 0x85, 0xee, 0xf3, 0xc4, 0xd6, 0xd2, 0x5e, 0x8a, 0x6f, 0xe1, 0x6d,
	0xfd, 0xe3, 0x2f, 0x72, 0x4c, 0xa1, 0xd6, 0x23, 0x47, 0xe1, 0x53, 0x2a, 0x8b, 0x44, 0x0d, 0xaf,
	0xad, 0x9b, 0xff, 0x69, 0x4d, 0x45, 0x2a, 0x4f, 0xd2, 0xed, 0x3a, 0xf5, 0x72, 0x5b, 0x0d, 0xb4,
	0x67, 0x1c, 0x25, 0x7c, 0xd5, 0xfc, 0xa7, 0x51, 0x3e, 0xed, 0xf6, 0x1d, 0x2b, 0xeb, 0x8f, 0xc7,
	0x0e, 0x3c, 0x0d, 0xda, 0x37, 0x7d, 0x9a, 0x1e, 0x0e, 0xff, 0x2e, 0x6f, 0xfa, 0xbe, 0xe4, 0xac,
	0x47, 0x8d, 0x72, 0xf4, 0x2e, 0x89, 0xef, 0xeb, 0xd1, 0xaf, 0xf8, 0xc3, 0xe3, 0xdc, 0xe5, 0x8e,
	0xc8, 0x14, 0x57, 0x2b, 0xb8, 0x73, 0x56, 0x05, 0xae, 0x55, 0xa6, 0x97, 0xbb, 0x5e, 0x99, 0xbf,
	0xb9, 0xee, 0x6e, 0xf8, 0xd3, 0xe3, 0x4c, 0xc7, 0x57, 0xe7, 0x16, 0x37, 0x9b, 0x7f, 0x37, 0x60,
	0xcf, 0x95, 0xbe, 0xc8, 0x55, 0xbc, 0xc8, 0xf1, 0xa2, 0xbd, 0xc0, 0xd1, 0x99, 0xad, 0x38, 0xa6,
	0xb3, 0x82, 0xae, 0xbf, 0xe8, 0x0c, 0x1b, 0x7e, 0x0f, 0xbc, 0xf7, 0x5e, 0x9a, 0xd2, 0x5f, 0x8c,
	0x2d, 0x8f, 0x70, 0xd5, 0x3f, 0x0f, 0x17, 0xf9, 0x39, 0xf9, 0x6c, 0xe7, 0x02, 0x6b, 0x55, 0x20,
	0xe4, 0x38, 0x1f, 0xb0, 0x0b, 0xb9, 0x06, 0xe3, 0xfa, 0xc3, 0x0a, 0xde, 0xbb, 0xd1, 0x3c, 0x83,
	0x67, 0x8e, 0x5b, 0x57, 0xdb, 0xe4, 0x73, 0xe1, 0x89, 0x39, 0x01, 0xa5, 0x39, 0xe3, 0xe6, 0x2e,
	0xc3, 0xd4, 0x13, 0x7c, 0x91, 0x6a, 0xc8, 0x54, 0x9e, 0x5f, 0x72, 0x27, 0x16, 0x1b, 0xff, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xd4, 0xe8, 0x09, 0xb4, 0x14, 0x06, 0x00, 0x00,
}
