// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lobby_club.proto

package club

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgClubReply struct {
	ReplyCode            *int32   `protobuf:"varint,1,req,name=replyCode" json:"replyCode,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClubReply) Reset()         { *m = MsgClubReply{} }
func (m *MsgClubReply) String() string { return proto.CompactTextString(m) }
func (*MsgClubReply) ProtoMessage()    {}
func (*MsgClubReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{0}
}
func (m *MsgClubReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubReply.Unmarshal(m, b)
}
func (m *MsgClubReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubReply.Marshal(b, m, deterministic)
}
func (m *MsgClubReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubReply.Merge(m, src)
}
func (m *MsgClubReply) XXX_Size() int {
	return xxx_messageInfo_MsgClubReply.Size(m)
}
func (m *MsgClubReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubReply proto.InternalMessageInfo

func (m *MsgClubReply) GetReplyCode() int32 {
	if m != nil && m.ReplyCode != nil {
		return *m.ReplyCode
	}
	return 0
}

func (m *MsgClubReply) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type MsgClubDisplayInfo struct {
	Nick                 *string  `protobuf:"bytes,1,req,name=nick" json:"nick,omitempty"`
	Gender               *uint32  `protobuf:"varint,2,opt,name=gender" json:"gender,omitempty"`
	HeadIconURL          *string  `protobuf:"bytes,3,opt,name=headIconURL" json:"headIconURL,omitempty"`
	AvatarID             *int32   `protobuf:"varint,4,opt,name=avatarID" json:"avatarID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClubDisplayInfo) Reset()         { *m = MsgClubDisplayInfo{} }
func (m *MsgClubDisplayInfo) String() string { return proto.CompactTextString(m) }
func (*MsgClubDisplayInfo) ProtoMessage()    {}
func (*MsgClubDisplayInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{1}
}
func (m *MsgClubDisplayInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubDisplayInfo.Unmarshal(m, b)
}
func (m *MsgClubDisplayInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubDisplayInfo.Marshal(b, m, deterministic)
}
func (m *MsgClubDisplayInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubDisplayInfo.Merge(m, src)
}
func (m *MsgClubDisplayInfo) XXX_Size() int {
	return xxx_messageInfo_MsgClubDisplayInfo.Size(m)
}
func (m *MsgClubDisplayInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubDisplayInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubDisplayInfo proto.InternalMessageInfo

func (m *MsgClubDisplayInfo) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *MsgClubDisplayInfo) GetGender() uint32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *MsgClubDisplayInfo) GetHeadIconURL() string {
	if m != nil && m.HeadIconURL != nil {
		return *m.HeadIconURL
	}
	return ""
}

func (m *MsgClubDisplayInfo) GetAvatarID() int32 {
	if m != nil && m.AvatarID != nil {
		return *m.AvatarID
	}
	return 0
}

// 俱乐部成员信息
type MsgClubMemberInfo struct {
	UserID               *string             `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	DisplayInfo          *MsgClubDisplayInfo `protobuf:"bytes,2,opt,name=displayInfo" json:"displayInfo,omitempty"`
	Online               *bool               `protobuf:"varint,3,opt,name=online" json:"online,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MsgClubMemberInfo) Reset()         { *m = MsgClubMemberInfo{} }
func (m *MsgClubMemberInfo) String() string { return proto.CompactTextString(m) }
func (*MsgClubMemberInfo) ProtoMessage()    {}
func (*MsgClubMemberInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{2}
}
func (m *MsgClubMemberInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubMemberInfo.Unmarshal(m, b)
}
func (m *MsgClubMemberInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubMemberInfo.Marshal(b, m, deterministic)
}
func (m *MsgClubMemberInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubMemberInfo.Merge(m, src)
}
func (m *MsgClubMemberInfo) XXX_Size() int {
	return xxx_messageInfo_MsgClubMemberInfo.Size(m)
}
func (m *MsgClubMemberInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubMemberInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubMemberInfo proto.InternalMessageInfo

func (m *MsgClubMemberInfo) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *MsgClubMemberInfo) GetDisplayInfo() *MsgClubDisplayInfo {
	if m != nil {
		return m.DisplayInfo
	}
	return nil
}

func (m *MsgClubMemberInfo) GetOnline() bool {
	if m != nil && m.Online != nil {
		return *m.Online
	}
	return false
}

// 俱乐部的基本信息
type MsgClubBaseInfo struct {
	ClubNumber           *string  `protobuf:"bytes,1,req,name=clubNumber" json:"clubNumber,omitempty"`
	ClubName             *string  `protobuf:"bytes,2,opt,name=clubName" json:"clubName,omitempty"`
	ClubID               *string  `protobuf:"bytes,3,opt,name=clubID" json:"clubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClubBaseInfo) Reset()         { *m = MsgClubBaseInfo{} }
func (m *MsgClubBaseInfo) String() string { return proto.CompactTextString(m) }
func (*MsgClubBaseInfo) ProtoMessage()    {}
func (*MsgClubBaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{3}
}
func (m *MsgClubBaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubBaseInfo.Unmarshal(m, b)
}
func (m *MsgClubBaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubBaseInfo.Marshal(b, m, deterministic)
}
func (m *MsgClubBaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubBaseInfo.Merge(m, src)
}
func (m *MsgClubBaseInfo) XXX_Size() int {
	return xxx_messageInfo_MsgClubBaseInfo.Size(m)
}
func (m *MsgClubBaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubBaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubBaseInfo proto.InternalMessageInfo

func (m *MsgClubBaseInfo) GetClubNumber() string {
	if m != nil && m.ClubNumber != nil {
		return *m.ClubNumber
	}
	return ""
}

func (m *MsgClubBaseInfo) GetClubName() string {
	if m != nil && m.ClubName != nil {
		return *m.ClubName
	}
	return ""
}

func (m *MsgClubBaseInfo) GetClubID() string {
	if m != nil && m.ClubID != nil {
		return *m.ClubID
	}
	return ""
}

// 俱乐部操作通用回复，免得定义太多消息体
type MsgCubOperGenericReply struct {
	ErrorCode            *int32   `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	Extra                *string  `protobuf:"bytes,2,opt,name=extra" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCubOperGenericReply) Reset()         { *m = MsgCubOperGenericReply{} }
func (m *MsgCubOperGenericReply) String() string { return proto.CompactTextString(m) }
func (*MsgCubOperGenericReply) ProtoMessage()    {}
func (*MsgCubOperGenericReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{4}
}
func (m *MsgCubOperGenericReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCubOperGenericReply.Unmarshal(m, b)
}
func (m *MsgCubOperGenericReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCubOperGenericReply.Marshal(b, m, deterministic)
}
func (m *MsgCubOperGenericReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCubOperGenericReply.Merge(m, src)
}
func (m *MsgCubOperGenericReply) XXX_Size() int {
	return xxx_messageInfo_MsgCubOperGenericReply.Size(m)
}
func (m *MsgCubOperGenericReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCubOperGenericReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCubOperGenericReply proto.InternalMessageInfo

func (m *MsgCubOperGenericReply) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *MsgCubOperGenericReply) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

// 俱乐部信息
type MsgClubInfo struct {
	BaseInfo             *MsgClubBaseInfo `protobuf:"bytes,1,opt,name=baseInfo" json:"baseInfo,omitempty"`
	CreatorUserID        *string          `protobuf:"bytes,2,opt,name=creatorUserID" json:"creatorUserID,omitempty"`
	ClubLevel            *int32           `protobuf:"varint,3,opt,name=clubLevel" json:"clubLevel,omitempty"`
	Points               *int32           `protobuf:"varint,4,opt,name=points" json:"points,omitempty"`
	Wanka                *int32           `protobuf:"varint,5,opt,name=wanka" json:"wanka,omitempty"`
	Candy                *int32           `protobuf:"varint,6,opt,name=candy" json:"candy,omitempty"`
	MaxMember            *int32           `protobuf:"varint,7,opt,name=maxMember" json:"maxMember,omitempty"`
	JoinForbit           *bool            `protobuf:"varint,8,opt,name=joinForbit" json:"joinForbit,omitempty"`
	HasUnReadEvents      *bool            `protobuf:"varint,9,opt,name=hasUnReadEvents" json:"hasUnReadEvents,omitempty"`
	CreateRoomOption     *int32           `protobuf:"varint,10,opt,name=createRoomOption" json:"createRoomOption,omitempty"`
	PayRoomOption        *int32           `protobuf:"varint,11,opt,name=payRoomOption" json:"payRoomOption,omitempty"`
	CreateTime           *int32           `protobuf:"varint,12,opt,name=createTime" json:"createTime,omitempty"`
	MemberCount          *int32           `protobuf:"varint,13,opt,name=memberCount" json:"memberCount,omitempty"`
	Managers             []string         `protobuf:"bytes,14,rep,name=managers" json:"managers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MsgClubInfo) Reset()         { *m = MsgClubInfo{} }
func (m *MsgClubInfo) String() string { return proto.CompactTextString(m) }
func (*MsgClubInfo) ProtoMessage()    {}
func (*MsgClubInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{5}
}
func (m *MsgClubInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubInfo.Unmarshal(m, b)
}
func (m *MsgClubInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubInfo.Marshal(b, m, deterministic)
}
func (m *MsgClubInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubInfo.Merge(m, src)
}
func (m *MsgClubInfo) XXX_Size() int {
	return xxx_messageInfo_MsgClubInfo.Size(m)
}
func (m *MsgClubInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubInfo proto.InternalMessageInfo

func (m *MsgClubInfo) GetBaseInfo() *MsgClubBaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

func (m *MsgClubInfo) GetCreatorUserID() string {
	if m != nil && m.CreatorUserID != nil {
		return *m.CreatorUserID
	}
	return ""
}

func (m *MsgClubInfo) GetClubLevel() int32 {
	if m != nil && m.ClubLevel != nil {
		return *m.ClubLevel
	}
	return 0
}

func (m *MsgClubInfo) GetPoints() int32 {
	if m != nil && m.Points != nil {
		return *m.Points
	}
	return 0
}

func (m *MsgClubInfo) GetWanka() int32 {
	if m != nil && m.Wanka != nil {
		return *m.Wanka
	}
	return 0
}

func (m *MsgClubInfo) GetCandy() int32 {
	if m != nil && m.Candy != nil {
		return *m.Candy
	}
	return 0
}

func (m *MsgClubInfo) GetMaxMember() int32 {
	if m != nil && m.MaxMember != nil {
		return *m.MaxMember
	}
	return 0
}

func (m *MsgClubInfo) GetJoinForbit() bool {
	if m != nil && m.JoinForbit != nil {
		return *m.JoinForbit
	}
	return false
}

func (m *MsgClubInfo) GetHasUnReadEvents() bool {
	if m != nil && m.HasUnReadEvents != nil {
		return *m.HasUnReadEvents
	}
	return false
}

func (m *MsgClubInfo) GetCreateRoomOption() int32 {
	if m != nil && m.CreateRoomOption != nil {
		return *m.CreateRoomOption
	}
	return 0
}

func (m *MsgClubInfo) GetPayRoomOption() int32 {
	if m != nil && m.PayRoomOption != nil {
		return *m.PayRoomOption
	}
	return 0
}

func (m *MsgClubInfo) GetCreateTime() int32 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *MsgClubInfo) GetMemberCount() int32 {
	if m != nil && m.MemberCount != nil {
		return *m.MemberCount
	}
	return 0
}

func (m *MsgClubInfo) GetManagers() []string {
	if m != nil {
		return m.Managers
	}
	return nil
}

// 加载自己的俱乐部
type MsgClubLoadMyClubsReply struct {
	Clubs                []*MsgClubInfo `protobuf:"bytes,1,rep,name=clubs" json:"clubs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MsgClubLoadMyClubsReply) Reset()         { *m = MsgClubLoadMyClubsReply{} }
func (m *MsgClubLoadMyClubsReply) String() string { return proto.CompactTextString(m) }
func (*MsgClubLoadMyClubsReply) ProtoMessage()    {}
func (*MsgClubLoadMyClubsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{6}
}
func (m *MsgClubLoadMyClubsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubLoadMyClubsReply.Unmarshal(m, b)
}
func (m *MsgClubLoadMyClubsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubLoadMyClubsReply.Marshal(b, m, deterministic)
}
func (m *MsgClubLoadMyClubsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubLoadMyClubsReply.Merge(m, src)
}
func (m *MsgClubLoadMyClubsReply) XXX_Size() int {
	return xxx_messageInfo_MsgClubLoadMyClubsReply.Size(m)
}
func (m *MsgClubLoadMyClubsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubLoadMyClubsReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubLoadMyClubsReply proto.InternalMessageInfo

func (m *MsgClubLoadMyClubsReply) GetClubs() []*MsgClubInfo {
	if m != nil {
		return m.Clubs
	}
	return nil
}

// 加载俱乐部更新回复
type MsgClubLoadUpdateReply struct {
	ClubsUpdated         []*MsgClubInfo `protobuf:"bytes,1,rep,name=clubsUpdated" json:"clubsUpdated,omitempty"`
	ClubIDsRemoved       []string       `protobuf:"bytes,2,rep,name=clubIDsRemoved" json:"clubIDsRemoved,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MsgClubLoadUpdateReply) Reset()         { *m = MsgClubLoadUpdateReply{} }
func (m *MsgClubLoadUpdateReply) String() string { return proto.CompactTextString(m) }
func (*MsgClubLoadUpdateReply) ProtoMessage()    {}
func (*MsgClubLoadUpdateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{7}
}
func (m *MsgClubLoadUpdateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubLoadUpdateReply.Unmarshal(m, b)
}
func (m *MsgClubLoadUpdateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubLoadUpdateReply.Marshal(b, m, deterministic)
}
func (m *MsgClubLoadUpdateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubLoadUpdateReply.Merge(m, src)
}
func (m *MsgClubLoadUpdateReply) XXX_Size() int {
	return xxx_messageInfo_MsgClubLoadUpdateReply.Size(m)
}
func (m *MsgClubLoadUpdateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubLoadUpdateReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubLoadUpdateReply proto.InternalMessageInfo

func (m *MsgClubLoadUpdateReply) GetClubsUpdated() []*MsgClubInfo {
	if m != nil {
		return m.ClubsUpdated
	}
	return nil
}

func (m *MsgClubLoadUpdateReply) GetClubIDsRemoved() []string {
	if m != nil {
		return m.ClubIDsRemoved
	}
	return nil
}

// 服务器回复请求成员列表
type MsgClubLoadMembersReply struct {
	Members              []*MsgClubMemberInfo `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
	Cursor               *int32               `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MsgClubLoadMembersReply) Reset()         { *m = MsgClubLoadMembersReply{} }
func (m *MsgClubLoadMembersReply) String() string { return proto.CompactTextString(m) }
func (*MsgClubLoadMembersReply) ProtoMessage()    {}
func (*MsgClubLoadMembersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{8}
}
func (m *MsgClubLoadMembersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubLoadMembersReply.Unmarshal(m, b)
}
func (m *MsgClubLoadMembersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubLoadMembersReply.Marshal(b, m, deterministic)
}
func (m *MsgClubLoadMembersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubLoadMembersReply.Merge(m, src)
}
func (m *MsgClubLoadMembersReply) XXX_Size() int {
	return xxx_messageInfo_MsgClubLoadMembersReply.Size(m)
}
func (m *MsgClubLoadMembersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubLoadMembersReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubLoadMembersReply proto.InternalMessageInfo

func (m *MsgClubLoadMembersReply) GetMembers() []*MsgClubMemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *MsgClubLoadMembersReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

// 创建俱乐部服务器给客户端的回复
type MsgCreateClubReply struct {
	ClubInfo             *MsgClubInfo `protobuf:"bytes,1,opt,name=clubInfo" json:"clubInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MsgCreateClubReply) Reset()         { *m = MsgCreateClubReply{} }
func (m *MsgCreateClubReply) String() string { return proto.CompactTextString(m) }
func (*MsgCreateClubReply) ProtoMessage()    {}
func (*MsgCreateClubReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{9}
}
func (m *MsgCreateClubReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateClubReply.Unmarshal(m, b)
}
func (m *MsgCreateClubReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateClubReply.Marshal(b, m, deterministic)
}
func (m *MsgCreateClubReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateClubReply.Merge(m, src)
}
func (m *MsgCreateClubReply) XXX_Size() int {
	return xxx_messageInfo_MsgCreateClubReply.Size(m)
}
func (m *MsgCreateClubReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateClubReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateClubReply proto.InternalMessageInfo

func (m *MsgCreateClubReply) GetClubInfo() *MsgClubInfo {
	if m != nil {
		return m.ClubInfo
	}
	return nil
}

// 俱乐部事件，注意和MsgClubNotification不同，事件是系统生成，不可设置
type MsgClubEvent struct {
	EvtType              *int32              `protobuf:"varint,1,req,name=evtType" json:"evtType,omitempty"`
	Id                   *uint32             `protobuf:"varint,2,req,name=Id" json:"Id,omitempty"`
	GeneratedTime        *uint32             `protobuf:"varint,3,req,name=generatedTime" json:"generatedTime,omitempty"`
	To                   *string             `protobuf:"bytes,4,opt,name=to" json:"to,omitempty"`
	Content              []byte              `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	Unread               *bool               `protobuf:"varint,6,opt,name=unread" json:"unread,omitempty"`
	NeedHandle           *bool               `protobuf:"varint,7,opt,name=needHandle" json:"needHandle,omitempty"`
	UserID1              *string             `protobuf:"bytes,8,opt,name=userID1" json:"userID1,omitempty"`
	DisplayInfo1         *MsgClubDisplayInfo `protobuf:"bytes,9,opt,name=displayInfo1" json:"displayInfo1,omitempty"`
	ApprovalResult       *int32              `protobuf:"varint,10,opt,name=approvalResult" json:"approvalResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MsgClubEvent) Reset()         { *m = MsgClubEvent{} }
func (m *MsgClubEvent) String() string { return proto.CompactTextString(m) }
func (*MsgClubEvent) ProtoMessage()    {}
func (*MsgClubEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{10}
}
func (m *MsgClubEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubEvent.Unmarshal(m, b)
}
func (m *MsgClubEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubEvent.Marshal(b, m, deterministic)
}
func (m *MsgClubEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubEvent.Merge(m, src)
}
func (m *MsgClubEvent) XXX_Size() int {
	return xxx_messageInfo_MsgClubEvent.Size(m)
}
func (m *MsgClubEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubEvent proto.InternalMessageInfo

func (m *MsgClubEvent) GetEvtType() int32 {
	if m != nil && m.EvtType != nil {
		return *m.EvtType
	}
	return 0
}

func (m *MsgClubEvent) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MsgClubEvent) GetGeneratedTime() uint32 {
	if m != nil && m.GeneratedTime != nil {
		return *m.GeneratedTime
	}
	return 0
}

func (m *MsgClubEvent) GetTo() string {
	if m != nil && m.To != nil {
		return *m.To
	}
	return ""
}

func (m *MsgClubEvent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MsgClubEvent) GetUnread() bool {
	if m != nil && m.Unread != nil {
		return *m.Unread
	}
	return false
}

func (m *MsgClubEvent) GetNeedHandle() bool {
	if m != nil && m.NeedHandle != nil {
		return *m.NeedHandle
	}
	return false
}

func (m *MsgClubEvent) GetUserID1() string {
	if m != nil && m.UserID1 != nil {
		return *m.UserID1
	}
	return ""
}

func (m *MsgClubEvent) GetDisplayInfo1() *MsgClubDisplayInfo {
	if m != nil {
		return m.DisplayInfo1
	}
	return nil
}

func (m *MsgClubEvent) GetApprovalResult() int32 {
	if m != nil && m.ApprovalResult != nil {
		return *m.ApprovalResult
	}
	return 0
}

// 服务器回复请求事件列表
type MsgClubLoadEventsReply struct {
	Events               []*MsgClubEvent `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	Cursor               *int32          `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MsgClubLoadEventsReply) Reset()         { *m = MsgClubLoadEventsReply{} }
func (m *MsgClubLoadEventsReply) String() string { return proto.CompactTextString(m) }
func (*MsgClubLoadEventsReply) ProtoMessage()    {}
func (*MsgClubLoadEventsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{11}
}
func (m *MsgClubLoadEventsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubLoadEventsReply.Unmarshal(m, b)
}
func (m *MsgClubLoadEventsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubLoadEventsReply.Marshal(b, m, deterministic)
}
func (m *MsgClubLoadEventsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubLoadEventsReply.Merge(m, src)
}
func (m *MsgClubLoadEventsReply) XXX_Size() int {
	return xxx_messageInfo_MsgClubLoadEventsReply.Size(m)
}
func (m *MsgClubLoadEventsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubLoadEventsReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubLoadEventsReply proto.InternalMessageInfo

func (m *MsgClubLoadEventsReply) GetEvents() []*MsgClubEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *MsgClubLoadEventsReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

// 俱乐部房间信息
type MsgClubRoomInfo struct {
	RoomType             *int32   `protobuf:"varint,1,req,name=roomType" json:"roomType,omitempty"`
	RoomRuleJSON         *string  `protobuf:"bytes,2,opt,name=roomRuleJSON" json:"roomRuleJSON,omitempty"`
	PlayerNumber         *int32   `protobuf:"varint,3,opt,name=playerNumber" json:"playerNumber,omitempty"`
	RoomState            *int32   `protobuf:"varint,4,opt,name=roomState" json:"roomState,omitempty"`
	RoomNumber           *string  `protobuf:"bytes,5,opt,name=roomNumber" json:"roomNumber,omitempty"`
	RoomUUID             *string  `protobuf:"bytes,6,opt,name=roomUUID" json:"roomUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClubRoomInfo) Reset()         { *m = MsgClubRoomInfo{} }
func (m *MsgClubRoomInfo) String() string { return proto.CompactTextString(m) }
func (*MsgClubRoomInfo) ProtoMessage()    {}
func (*MsgClubRoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{12}
}
func (m *MsgClubRoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubRoomInfo.Unmarshal(m, b)
}
func (m *MsgClubRoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubRoomInfo.Marshal(b, m, deterministic)
}
func (m *MsgClubRoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubRoomInfo.Merge(m, src)
}
func (m *MsgClubRoomInfo) XXX_Size() int {
	return xxx_messageInfo_MsgClubRoomInfo.Size(m)
}
func (m *MsgClubRoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubRoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubRoomInfo proto.InternalMessageInfo

func (m *MsgClubRoomInfo) GetRoomType() int32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return 0
}

func (m *MsgClubRoomInfo) GetRoomRuleJSON() string {
	if m != nil && m.RoomRuleJSON != nil {
		return *m.RoomRuleJSON
	}
	return ""
}

func (m *MsgClubRoomInfo) GetPlayerNumber() int32 {
	if m != nil && m.PlayerNumber != nil {
		return *m.PlayerNumber
	}
	return 0
}

func (m *MsgClubRoomInfo) GetRoomState() int32 {
	if m != nil && m.RoomState != nil {
		return *m.RoomState
	}
	return 0
}

func (m *MsgClubRoomInfo) GetRoomNumber() string {
	if m != nil && m.RoomNumber != nil {
		return *m.RoomNumber
	}
	return ""
}

func (m *MsgClubRoomInfo) GetRoomUUID() string {
	if m != nil && m.RoomUUID != nil {
		return *m.RoomUUID
	}
	return ""
}

// 服务器回复请求俱乐部房间列表
type MsgClubLoadRoomsReply struct {
	Rooms                []*MsgClubRoomInfo `protobuf:"bytes,1,rep,name=rooms" json:"rooms,omitempty"`
	Cursor               *int32             `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	TotalRoomCount       *int32             `protobuf:"varint,3,opt,name=totalRoomCount" json:"totalRoomCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MsgClubLoadRoomsReply) Reset()         { *m = MsgClubLoadRoomsReply{} }
func (m *MsgClubLoadRoomsReply) String() string { return proto.CompactTextString(m) }
func (*MsgClubLoadRoomsReply) ProtoMessage()    {}
func (*MsgClubLoadRoomsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{13}
}
func (m *MsgClubLoadRoomsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubLoadRoomsReply.Unmarshal(m, b)
}
func (m *MsgClubLoadRoomsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubLoadRoomsReply.Marshal(b, m, deterministic)
}
func (m *MsgClubLoadRoomsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubLoadRoomsReply.Merge(m, src)
}
func (m *MsgClubLoadRoomsReply) XXX_Size() int {
	return xxx_messageInfo_MsgClubLoadRoomsReply.Size(m)
}
func (m *MsgClubLoadRoomsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubLoadRoomsReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubLoadRoomsReply proto.InternalMessageInfo

func (m *MsgClubLoadRoomsReply) GetRooms() []*MsgClubRoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *MsgClubLoadRoomsReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

func (m *MsgClubLoadRoomsReply) GetTotalRoomCount() int32 {
	if m != nil && m.TotalRoomCount != nil {
		return *m.TotalRoomCount
	}
	return 0
}

// 俱乐部基金事件
type MsgClubFundEvent struct {
	EvtType              *int32   `protobuf:"varint,1,req,name=evtType" json:"evtType,omitempty"`
	GeneratedTime        *uint32  `protobuf:"varint,2,req,name=generatedTime" json:"generatedTime,omitempty"`
	UserID               *string  `protobuf:"bytes,3,req,name=userID" json:"userID,omitempty"`
	Amount               *int32   `protobuf:"varint,4,req,name=amount" json:"amount,omitempty"`
	Total                *int32   `protobuf:"varint,5,req,name=total" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClubFundEvent) Reset()         { *m = MsgClubFundEvent{} }
func (m *MsgClubFundEvent) String() string { return proto.CompactTextString(m) }
func (*MsgClubFundEvent) ProtoMessage()    {}
func (*MsgClubFundEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{14}
}
func (m *MsgClubFundEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubFundEvent.Unmarshal(m, b)
}
func (m *MsgClubFundEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubFundEvent.Marshal(b, m, deterministic)
}
func (m *MsgClubFundEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubFundEvent.Merge(m, src)
}
func (m *MsgClubFundEvent) XXX_Size() int {
	return xxx_messageInfo_MsgClubFundEvent.Size(m)
}
func (m *MsgClubFundEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubFundEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubFundEvent proto.InternalMessageInfo

func (m *MsgClubFundEvent) GetEvtType() int32 {
	if m != nil && m.EvtType != nil {
		return *m.EvtType
	}
	return 0
}

func (m *MsgClubFundEvent) GetGeneratedTime() uint32 {
	if m != nil && m.GeneratedTime != nil {
		return *m.GeneratedTime
	}
	return 0
}

func (m *MsgClubFundEvent) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *MsgClubFundEvent) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *MsgClubFundEvent) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

// 加载俱乐部基金事件的回复
type MsgClubLoadFundEventsReply struct {
	Events               []*MsgClubFundEvent `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	Cursor               *int32              `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MsgClubLoadFundEventsReply) Reset()         { *m = MsgClubLoadFundEventsReply{} }
func (m *MsgClubLoadFundEventsReply) String() string { return proto.CompactTextString(m) }
func (*MsgClubLoadFundEventsReply) ProtoMessage()    {}
func (*MsgClubLoadFundEventsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{15}
}
func (m *MsgClubLoadFundEventsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubLoadFundEventsReply.Unmarshal(m, b)
}
func (m *MsgClubLoadFundEventsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubLoadFundEventsReply.Marshal(b, m, deterministic)
}
func (m *MsgClubLoadFundEventsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubLoadFundEventsReply.Merge(m, src)
}
func (m *MsgClubLoadFundEventsReply) XXX_Size() int {
	return xxx_messageInfo_MsgClubLoadFundEventsReply.Size(m)
}
func (m *MsgClubLoadFundEventsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubLoadFundEventsReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubLoadFundEventsReply proto.InternalMessageInfo

func (m *MsgClubLoadFundEventsReply) GetEvents() []*MsgClubFundEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *MsgClubLoadFundEventsReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

// 加载回播房间的回复
type MsgClubLoadReplayRoomsReply struct {
	GZipBytes            []byte   `protobuf:"bytes,1,opt,name=gZipBytes" json:"gZipBytes,omitempty"`
	Cursor               *int32   `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClubLoadReplayRoomsReply) Reset()         { *m = MsgClubLoadReplayRoomsReply{} }
func (m *MsgClubLoadReplayRoomsReply) String() string { return proto.CompactTextString(m) }
func (*MsgClubLoadReplayRoomsReply) ProtoMessage()    {}
func (*MsgClubLoadReplayRoomsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{16}
}
func (m *MsgClubLoadReplayRoomsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubLoadReplayRoomsReply.Unmarshal(m, b)
}
func (m *MsgClubLoadReplayRoomsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubLoadReplayRoomsReply.Marshal(b, m, deterministic)
}
func (m *MsgClubLoadReplayRoomsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubLoadReplayRoomsReply.Merge(m, src)
}
func (m *MsgClubLoadReplayRoomsReply) XXX_Size() int {
	return xxx_messageInfo_MsgClubLoadReplayRoomsReply.Size(m)
}
func (m *MsgClubLoadReplayRoomsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubLoadReplayRoomsReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubLoadReplayRoomsReply proto.InternalMessageInfo

func (m *MsgClubLoadReplayRoomsReply) GetGZipBytes() []byte {
	if m != nil {
		return m.GZipBytes
	}
	return nil
}

func (m *MsgClubLoadReplayRoomsReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

// 牌友群申请记录
type MsgClubApplyRecord struct {
	ClubID               *string  `protobuf:"bytes,1,req,name=clubID" json:"clubID,omitempty"`
	ClubNumber           *string  `protobuf:"bytes,2,opt,name=clubNumber" json:"clubNumber,omitempty"`
	ClubName             *string  `protobuf:"bytes,3,opt,name=clubName" json:"clubName,omitempty"`
	ApprovalResult       *int32   `protobuf:"varint,4,opt,name=approvalResult" json:"approvalResult,omitempty"`
	EventID              *int32   `protobuf:"varint,5,opt,name=eventID" json:"eventID,omitempty"`
	TimeStamp            *int64   `protobuf:"varint,6,opt,name=timeStamp" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClubApplyRecord) Reset()         { *m = MsgClubApplyRecord{} }
func (m *MsgClubApplyRecord) String() string { return proto.CompactTextString(m) }
func (*MsgClubApplyRecord) ProtoMessage()    {}
func (*MsgClubApplyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{17}
}
func (m *MsgClubApplyRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubApplyRecord.Unmarshal(m, b)
}
func (m *MsgClubApplyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubApplyRecord.Marshal(b, m, deterministic)
}
func (m *MsgClubApplyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubApplyRecord.Merge(m, src)
}
func (m *MsgClubApplyRecord) XXX_Size() int {
	return xxx_messageInfo_MsgClubApplyRecord.Size(m)
}
func (m *MsgClubApplyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubApplyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubApplyRecord proto.InternalMessageInfo

func (m *MsgClubApplyRecord) GetClubID() string {
	if m != nil && m.ClubID != nil {
		return *m.ClubID
	}
	return ""
}

func (m *MsgClubApplyRecord) GetClubNumber() string {
	if m != nil && m.ClubNumber != nil {
		return *m.ClubNumber
	}
	return ""
}

func (m *MsgClubApplyRecord) GetClubName() string {
	if m != nil && m.ClubName != nil {
		return *m.ClubName
	}
	return ""
}

func (m *MsgClubApplyRecord) GetApprovalResult() int32 {
	if m != nil && m.ApprovalResult != nil {
		return *m.ApprovalResult
	}
	return 0
}

func (m *MsgClubApplyRecord) GetEventID() int32 {
	if m != nil && m.EventID != nil {
		return *m.EventID
	}
	return 0
}

func (m *MsgClubApplyRecord) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

type MsgClubLoadApplyRecordReply struct {
	Records              []*MsgClubApplyRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
	Cursor               *int32                `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MsgClubLoadApplyRecordReply) Reset()         { *m = MsgClubLoadApplyRecordReply{} }
func (m *MsgClubLoadApplyRecordReply) String() string { return proto.CompactTextString(m) }
func (*MsgClubLoadApplyRecordReply) ProtoMessage()    {}
func (*MsgClubLoadApplyRecordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{18}
}
func (m *MsgClubLoadApplyRecordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubLoadApplyRecordReply.Unmarshal(m, b)
}
func (m *MsgClubLoadApplyRecordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubLoadApplyRecordReply.Marshal(b, m, deterministic)
}
func (m *MsgClubLoadApplyRecordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubLoadApplyRecordReply.Merge(m, src)
}
func (m *MsgClubLoadApplyRecordReply) XXX_Size() int {
	return xxx_messageInfo_MsgClubLoadApplyRecordReply.Size(m)
}
func (m *MsgClubLoadApplyRecordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubLoadApplyRecordReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubLoadApplyRecordReply proto.InternalMessageInfo

func (m *MsgClubLoadApplyRecordReply) GetRecords() []*MsgClubApplyRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *MsgClubLoadApplyRecordReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

type MsgClubNotify struct {
	NotifyType           *int32   `protobuf:"varint,1,req,name=notifyType" json:"notifyType,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClubNotify) Reset()         { *m = MsgClubNotify{} }
func (m *MsgClubNotify) String() string { return proto.CompactTextString(m) }
func (*MsgClubNotify) ProtoMessage()    {}
func (*MsgClubNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b10ad64e8169303, []int{19}
}
func (m *MsgClubNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClubNotify.Unmarshal(m, b)
}
func (m *MsgClubNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClubNotify.Marshal(b, m, deterministic)
}
func (m *MsgClubNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClubNotify.Merge(m, src)
}
func (m *MsgClubNotify) XXX_Size() int {
	return xxx_messageInfo_MsgClubNotify.Size(m)
}
func (m *MsgClubNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClubNotify.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClubNotify proto.InternalMessageInfo

func (m *MsgClubNotify) GetNotifyType() int32 {
	if m != nil && m.NotifyType != nil {
		return *m.NotifyType
	}
	return 0
}

func (m *MsgClubNotify) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgClubReply)(nil), "club.MsgClubReply")
	proto.RegisterType((*MsgClubDisplayInfo)(nil), "club.MsgClubDisplayInfo")
	proto.RegisterType((*MsgClubMemberInfo)(nil), "club.MsgClubMemberInfo")
	proto.RegisterType((*MsgClubBaseInfo)(nil), "club.MsgClubBaseInfo")
	proto.RegisterType((*MsgCubOperGenericReply)(nil), "club.MsgCubOperGenericReply")
	proto.RegisterType((*MsgClubInfo)(nil), "club.MsgClubInfo")
	proto.RegisterType((*MsgClubLoadMyClubsReply)(nil), "club.MsgClubLoadMyClubsReply")
	proto.RegisterType((*MsgClubLoadUpdateReply)(nil), "club.MsgClubLoadUpdateReply")
	proto.RegisterType((*MsgClubLoadMembersReply)(nil), "club.MsgClubLoadMembersReply")
	proto.RegisterType((*MsgCreateClubReply)(nil), "club.MsgCreateClubReply")
	proto.RegisterType((*MsgClubEvent)(nil), "club.MsgClubEvent")
	proto.RegisterType((*MsgClubLoadEventsReply)(nil), "club.MsgClubLoadEventsReply")
	proto.RegisterType((*MsgClubRoomInfo)(nil), "club.MsgClubRoomInfo")
	proto.RegisterType((*MsgClubLoadRoomsReply)(nil), "club.MsgClubLoadRoomsReply")
	proto.RegisterType((*MsgClubFundEvent)(nil), "club.MsgClubFundEvent")
	proto.RegisterType((*MsgClubLoadFundEventsReply)(nil), "club.MsgClubLoadFundEventsReply")
	proto.RegisterType((*MsgClubLoadReplayRoomsReply)(nil), "club.MsgClubLoadReplayRoomsReply")
	proto.RegisterType((*MsgClubApplyRecord)(nil), "club.MsgClubApplyRecord")
	proto.RegisterType((*MsgClubLoadApplyRecordReply)(nil), "club.MsgClubLoadApplyRecordReply")
	proto.RegisterType((*MsgClubNotify)(nil), "club.MsgClubNotify")
}

func init() { proto.RegisterFile("lobby_club.proto", fileDescriptor_3b10ad64e8169303) }

var fileDescriptor_3b10ad64e8169303 = []byte{
	// 965 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x86, 0x24, 0xd3, 0x16, 0x47, 0x94, 0x2c, 0x31, 0xb1, 0x4d, 0xb4, 0x17, 0x81, 0x2d, 0x1a,
	0xf5, 0x50, 0x03, 0x31, 0x7a, 0x69, 0x7b, 0x69, 0x63, 0x35, 0xa9, 0x0a, 0xff, 0x00, 0xb2, 0x05,
	0x34, 0xbd, 0x14, 0x2b, 0x72, 0xa2, 0xb0, 0x21, 0x77, 0x89, 0xe5, 0x52, 0x0d, 0x5f, 0xa0, 0xe8,
	0x33, 0xf5, 0x59, 0xfa, 0x30, 0xc5, 0xce, 0x2e, 0x65, 0x52, 0x4e, 0x72, 0x13, 0x47, 0x3b, 0xb3,
	0xdf, 0xf7, 0xcd, 0x37, 0xb3, 0x30, 0x4e, 0xc5, 0x7a, 0x5d, 0xfd, 0x11, 0xa5, 0xe5, 0xfa, 0x3c,
	0x97, 0x42, 0x09, 0xff, 0x40, 0xff, 0x0e, 0x2f, 0xc0, 0xbb, 0x2e, 0x36, 0x97, 0x69, 0xb9, 0x5e,
	0x62, 0x9e, 0x56, 0xfe, 0x04, 0x5c, 0xa9, 0x7f, 0x5c, 0x8a, 0x18, 0x83, 0xce, 0xb4, 0x3b, 0x73,
	0xfc, 0x63, 0x38, 0x8a, 0x04, 0x57, 0xc8, 0x55, 0xd0, 0x9d, 0x76, 0x66, 0x5e, 0xf8, 0x1a, 0x7c,
	0x9b, 0x33, 0x4f, 0x8a, 0x3c, 0x65, 0xd5, 0x82, 0xbf, 0x11, 0xbe, 0x07, 0x07, 0x3c, 0x89, 0xde,
	0x51, 0x92, 0xeb, 0x8f, 0xe0, 0x70, 0x83, 0x3c, 0x46, 0x49, 0x39, 0x43, 0xff, 0x09, 0x0c, 0xde,
	0x22, 0x8b, 0x17, 0x91, 0xe0, 0xab, 0xe5, 0x55, 0xd0, 0x9b, 0x76, 0x66, 0xae, 0x3f, 0x86, 0x3e,
	0xdb, 0x32, 0xc5, 0xe4, 0x62, 0x1e, 0x1c, 0x4c, 0x3b, 0x33, 0x27, 0x5c, 0xc3, 0xc4, 0x96, 0xbe,
	0xc6, 0x6c, 0x8d, 0x92, 0x2a, 0x8f, 0xe0, 0xb0, 0x2c, 0x50, 0x1f, 0x32, 0xb5, 0xbf, 0x81, 0x41,
	0xfc, 0x70, 0x31, 0x5d, 0x30, 0xb8, 0x08, 0xce, 0x89, 0xdb, 0x07, 0x80, 0x8d, 0xe0, 0x50, 0xf0,
	0x34, 0xe1, 0x48, 0xb7, 0xf6, 0xc3, 0x57, 0x70, 0x6c, 0x4f, 0xbd, 0x60, 0x05, 0xd2, 0x11, 0x1f,
	0x40, 0x67, 0xdf, 0x94, 0xfa, 0x4e, 0x7b, 0xcb, 0x18, 0xfa, 0x14, 0x63, 0x19, 0xd2, 0x15, 0xc4,
	0x49, 0x47, 0x16, 0x73, 0x03, 0x3f, 0xfc, 0x1e, 0x4e, 0x75, 0xa1, 0x72, 0x7d, 0x9b, 0xa3, 0x7c,
	0x85, 0x1c, 0x65, 0x12, 0xed, 0x54, 0x44, 0x29, 0x85, 0x6c, 0xa8, 0x38, 0x04, 0x07, 0xdf, 0x2b,
	0xc9, 0x4c, 0xad, 0xf0, 0xdf, 0x2e, 0x0c, 0x2c, 0x0a, 0x42, 0xf0, 0x0c, 0xfa, 0x6b, 0x8b, 0x26,
	0xe8, 0x10, 0xa1, 0x93, 0x16, 0xa1, 0x1d, 0xd4, 0x13, 0x18, 0x46, 0x12, 0x99, 0x12, 0x72, 0x65,
	0x34, 0x31, 0xd8, 0x26, 0xe0, 0xea, 0xe3, 0x57, 0xb8, 0xc5, 0x94, 0xe0, 0x39, 0x1a, 0x6e, 0x2e,
	0x12, 0xae, 0x0a, 0xa3, 0xad, 0x46, 0xf0, 0x17, 0xe3, 0xef, 0x58, 0xe0, 0xd4, 0x9f, 0x11, 0xe3,
	0x71, 0x15, 0x1c, 0xd2, 0xe7, 0x04, 0xdc, 0x8c, 0xbd, 0x37, 0xaa, 0x07, 0x47, 0x14, 0xf2, 0x01,
	0xfe, 0x14, 0x09, 0x7f, 0x29, 0xe4, 0x3a, 0x51, 0x41, 0x5f, 0x8b, 0xe7, 0x9f, 0xc1, 0xf1, 0x5b,
	0x56, 0xac, 0xf8, 0x12, 0x59, 0xfc, 0xf3, 0x16, 0x75, 0x75, 0x97, 0xfe, 0x08, 0x60, 0x4c, 0xb8,
	0x70, 0x29, 0x44, 0x76, 0x9b, 0xab, 0x44, 0xf0, 0x00, 0xa8, 0xcc, 0x09, 0x0c, 0x73, 0x56, 0x35,
	0xc2, 0x83, 0xba, 0xba, 0x49, 0xb8, 0x4f, 0x32, 0x0c, 0x3c, 0x8a, 0x3d, 0x81, 0x41, 0x46, 0x08,
	0x2e, 0x45, 0xc9, 0x55, 0x30, 0xa4, 0xe0, 0x18, 0xfa, 0x19, 0xe3, 0x6c, 0x83, 0xb2, 0x08, 0x46,
	0xd3, 0xde, 0xcc, 0x0d, 0x7f, 0x80, 0x33, 0x2b, 0xcb, 0x95, 0x60, 0xf1, 0x75, 0xa5, 0x7f, 0x15,
	0x46, 0xf9, 0x29, 0x38, 0x5a, 0x87, 0x22, 0xe8, 0x4c, 0x7b, 0xb3, 0xc1, 0xc5, 0xa4, 0x25, 0xa2,
	0x16, 0x30, 0x7c, 0x6d, 0xba, 0x66, 0x93, 0x57, 0x79, 0xac, 0x31, 0x53, 0xee, 0x33, 0xf0, 0x28,
	0xd7, 0xc4, 0xe2, 0x8f, 0x96, 0xf0, 0x4f, 0x61, 0x64, 0x8c, 0x50, 0x2c, 0x31, 0x13, 0x5b, 0x8c,
	0x83, 0x2e, 0xe1, 0xba, 0x6b, 0xe3, 0x22, 0x26, 0x16, 0xd7, 0x0c, 0x8e, 0x0c, 0xb3, 0x1a, 0xd9,
	0x59, 0xab, 0x6c, 0xdb, 0xed, 0x51, 0x29, 0x0b, 0x61, 0x26, 0xc7, 0x09, 0xbf, 0x33, 0xd3, 0x46,
	0x52, 0x3d, 0xcc, 0xe9, 0x17, 0xc6, 0x9d, 0x0d, 0xbf, 0x7c, 0x80, 0xea, 0x7f, 0x9d, 0xdd, 0x74,
	0x53, 0xaf, 0xf4, 0x28, 0xe3, 0x56, 0xdd, 0x57, 0x79, 0xed, 0x4a, 0x80, 0xee, 0x42, 0xa3, 0xef,
	0xce, 0x86, 0xba, 0x4f, 0x1b, 0x6d, 0x62, 0xcd, 0x9d, 0x7a, 0xd2, 0xa3, 0x30, 0x40, 0x57, 0x09,
	0xb2, 0x90, 0xdb, 0x5c, 0x05, 0xda, 0x44, 0x1e, 0x8d, 0x26, 0x97, 0xc8, 0x62, 0x72, 0x51, 0x5f,
	0x37, 0x95, 0x23, 0xc6, 0xbf, 0x30, 0x1e, 0xa7, 0x48, 0x36, 0xea, 0xeb, 0x24, 0x33, 0xbe, 0xcf,
	0xc9, 0x43, 0xae, 0x7f, 0x0e, 0x5e, 0x63, 0x7e, 0x9f, 0x93, 0x81, 0x3e, 0x35, 0xc0, 0xa7, 0x30,
	0x62, 0x79, 0x2e, 0xc5, 0x96, 0xa5, 0x4b, 0x2c, 0xca, 0x54, 0x19, 0x63, 0x85, 0x57, 0xad, 0x4e,
	0x1a, 0x37, 0x1a, 0x75, 0x42, 0x38, 0x44, 0x63, 0x4e, 0x23, 0xb6, 0xdf, 0xaa, 0x6d, 0xb4, 0xd8,
	0xd7, 0xf9, 0x9f, 0xce, 0x6e, 0x2f, 0x68, 0xaf, 0xd2, 0xcd, 0x63, 0xe8, 0x4b, 0x21, 0xb2, 0x86,
	0x60, 0x4f, 0xc1, 0xd3, 0x91, 0x65, 0x99, 0xe2, 0xaf, 0x77, 0xb7, 0x37, 0x76, 0xfa, 0x9e, 0x82,
	0xa7, 0xd1, 0xa2, 0xb4, 0x1b, 0xa4, 0x57, 0x8f, 0x94, 0x3e, 0x7b, 0xa7, 0x98, 0x42, 0x3b, 0x83,
	0x3e, 0x80, 0x0e, 0xd9, 0x63, 0x4e, 0xbd, 0x05, 0x75, 0x6c, 0xb5, 0x5a, 0xcc, 0x49, 0x45, 0x37,
	0x44, 0x38, 0x69, 0x10, 0xd3, 0x68, 0x2c, 0xaf, 0x2f, 0xc1, 0xd1, 0x47, 0x6b, 0x5a, 0xed, 0x15,
	0xb1, 0x43, 0xbd, 0xc7, 0x4c, 0xeb, 0xa7, 0x84, 0x62, 0xa9, 0x3e, 0x60, 0x06, 0x8b, 0xf0, 0x85,
	0x09, 0x8c, 0x6d, 0xea, 0xcb, 0x92, 0xc7, 0x1f, 0x71, 0xc8, 0x23, 0x57, 0x18, 0xb3, 0x3c, 0xec,
	0xe4, 0x5e, 0xbd, 0xef, 0x59, 0x46, 0xb5, 0x0f, 0xea, 0x75, 0x47, 0x77, 0x06, 0x8e, 0xfe, 0x0c,
	0xef, 0xe1, 0xb3, 0x06, 0xa3, 0xdd, 0x75, 0x96, 0xd6, 0x57, 0x7b, 0xed, 0x3a, 0x6d, 0xf1, 0x7a,
	0x00, 0xb7, 0xdf, 0xb2, 0x1f, 0xe1, 0xf3, 0xa6, 0x4e, 0xa8, 0x7b, 0xd0, 0x50, 0x6b, 0x02, 0xee,
	0xe6, 0xf7, 0x24, 0x7f, 0x51, 0x29, 0x2c, 0x68, 0x48, 0xbc, 0x47, 0x15, 0xfe, 0xee, 0xec, 0xde,
	0xb2, 0x9f, 0xf2, 0x3c, 0xad, 0x96, 0x18, 0x09, 0x19, 0x37, 0x36, 0xbd, 0x79, 0x0b, 0xda, 0xef,
	0x43, 0xb7, 0x6e, 0xdb, 0xee, 0x7d, 0x30, 0xcf, 0xd9, 0x63, 0x9f, 0x9a, 0xa6, 0x93, 0xa6, 0xc8,
	0xd5, 0x62, 0x6e, 0x57, 0xef, 0x04, 0x5c, 0x95, 0x64, 0x78, 0xa7, 0x58, 0x96, 0x53, 0xcb, 0x7b,
	0xe1, 0x6f, 0x2d, 0x2a, 0x0d, 0x2c, 0x86, 0xca, 0xd7, 0x70, 0x24, 0xe9, 0xb3, 0x96, 0xa8, 0x3d,
	0x2d, 0xfb, 0xd8, 0x9b, 0x14, 0xbf, 0x85, 0xa1, 0x3d, 0x75, 0x23, 0x54, 0xf2, 0xa6, 0xa2, 0x19,
	0xa5, 0x5f, 0x8d, 0x2e, 0xef, 0xbf, 0xf1, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x42, 0xde,
	0x7f, 0x30, 0x08, 0x00, 0x00,
}
